name: grain2mesh-env
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.9
  - cairo=1.16.0
  - contourpy=1.3.1
  - cpython=3.13.5
  - cycler=0.11.0
  - dav1d=1.2.1
  - deprecated=1.2.13
  - eigen=3.4.0
  - expat=2.7.0
  - ffmpeg=6.1.1
  - filelock=3.18.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.5.1
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icu=73.1
  - imageio=2.37.0
  - importlib-metadata=8.5.0
  - iniconfig=2.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.20
  - libprotobuf=5.29.3
  - librsvg=2.56.3
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - llvm-openmp=20.1.7
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=1.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.5.1
  - opentelemetry-api=1.30.0
  - optree=0.16.0
  - packaging=24.2
  - pango=1.50.7
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.1
  - pixman=0.46.2
  - pluggy=1.5.0
  - pthread-stubs=0.4
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pytest=8.4.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - pytorch=2.6.0
  - qtbase=6.7.2
  - readline=8.2
  - scikit-image=0.25.2
  - scipy=1.15.3
  - setuptools=72.1.0
  - six=1.17.0
  - sleef=3.8
  - sqlite=3.45.3
  - sympy=1.14.0
  - tesseract=5.2.0
  - tifffile=2025.2.18
  - tk=8.6.14
  - tornado=6.5.1
  - tqdm=4.67.1
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - asttokens==3.0.0
      - decorator==5.2.1
      - executing==2.2.0
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - matplotlib-inline==0.1.7
      - parso==0.8.4
      - pexpect==4.9.0
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - stack-data==0.6.3
      - traitlets==5.14.3
      - wcwidth==0.2.13

